name: aya_project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  map: any
  flutter:
    sdk: flutter

  # local databases
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2

  # state management
  provider: ^6.0.4
  flutter_bloc: ^8.1.1

  # network
  http: ^0.13.5

  # enviroment key management
  flutter_dotenv: ^5.0.2

  # screen helpers
  introduction_screen: ^3.0.2
  skeletons: ^0.0.3

  # svg
  flutter_svg: ^1.1.6

  # email
  mailer: ^6.0.0

  # pincode
  pin_code_fields: ^7.4.0

  # router
  auto_route: ^5.0.4

  # translater
  translator: ^0.1.7

  # icons
  cupertino_icons: ^1.0.2

  # for animations
  animations: ^2.0.7

  # rating
  rate: ^0.0.1

  # time picker
  intl: ^0.18.0

  # font awesome
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # for router
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # json
    - assets/json/
    # images
    - assets/images/logo/
    - assets/images/png/
    - assets/images/avatar/
    - assets/images/svg/

    # env file
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans-Regular.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-ExtraLight.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-LightItalic.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-Light.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-Black.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-Bold.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-SemiBold.ttf
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/abeezee/ABeeZee-Regular.ttf
        - asset: assets/fonts/abeezee/ABeeZee-Italic.ttf
    - family: BalooBhaina
      fonts:
        - asset: assets/fonts/BalooBhaina/BalooBhaina-Regular.ttf
        - asset: assets/fonts/BalooBhaina/BalooBhaina-Bold.ttf
        - asset: assets/fonts/BalooBhaina/BalooBhaina-ExtraBold.ttf
        - asset: assets/fonts/BalooBhaina/BalooBhaina-Medium.ttf
        - asset: assets/fonts/BalooBhaina/BalooBhaina-SemiBold.ttf
    - family: Georama
      fonts:
        - asset: assets/fonts/Georama/Georama-Black.ttf
        - asset: assets/fonts/Georama/Georama-Bold.ttf
        - asset: assets/fonts/Georama/Georama-ExtraBold.ttf
        - asset: assets/fonts/Georama/Georama-ExtraLight.ttf
        - asset: assets/fonts/Georama/Georama-Italic.ttf
        - asset: assets/fonts/Georama/Georama-Light.ttf
        - asset: assets/fonts/Georama/Georama-Medium.ttf
        - asset: assets/fonts/Georama/Georama-Regular.ttf
        - asset: assets/fonts/Georama/Georama-Semibold.ttf
        - asset: assets/fonts/Georama/Georama-Thin.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
